name: CI

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.13'

jobs:
  precommit:
    uses: ./.github/workflows/precommit.yml

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync
      - name: Test with uv
        run: uv run pytest
