
name: PreCommit Checks

env:
  PYTHON_VERSION: '3.13'

on: workflow_call

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run static code inspections
        run: uv run pre-commit run --all-files
