
name: PreCommit Checks

env:
  PYTHON_VERSION: '3.13'

on: workflow_call

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run static code inspections
        run: uv run pre-commit run --all-files
